module.exports = (sequelize, DataTypes) => {
    const Profile = sequelize.define(
        "Profile",
        {
            id: {
                type: DataTypes.TEXT,
                primaryKey: true,
                autoIncrement: true 
            },
            linkedin_id: DataTypes.BIGINT,
            parent_id: DataTypes.BIGINT,
            public_profile_id: DataTypes.BIGINT,
            linkedin_url: {
                type: DataTypes.TEXT,
                unique: true,
            },
            linkedin_shorthand_names: DataTypes.ARRAY(DataTypes.TEXT),
            historical_ids: DataTypes.ARRAY(DataTypes.BIGINT),
            full_name: DataTypes.TEXT,
            first_name: DataTypes.TEXT,
            middle_name: DataTypes.TEXT,
            first_name_initial: DataTypes.TEXT,
            middle_name_initial: DataTypes.TEXT,
            last_name_initial: DataTypes.TEXT,
            last_name: DataTypes.TEXT,
            headline: DataTypes.TEXT,
            location_country_iso2: DataTypes.TEXT,
            location_country_iso3: DataTypes.TEXT,
            location_full: DataTypes.TEXT,
            location_regions: DataTypes.ARRAY(DataTypes.TEXT),
            interests: DataTypes.ARRAY(DataTypes.TEXT),
            summary: DataTypes.TEXT,
            picture_url: DataTypes.TEXT,
            location_city: DataTypes.TEXT,
            location_state: DataTypes.TEXT,
            location_country: DataTypes.TEXT,
            active_experience_title: {
                type: DataTypes.TEXT,
                allowNull: false,
            },
            active_experience_department: DataTypes.TEXT,
            active_experience_management_level: DataTypes.TEXT,
            connections_count: DataTypes.INTEGER,
            followers_count: DataTypes.INTEGER,
            services: DataTypes.ARRAY(DataTypes.TEXT),
            total_experience_duration_months: DataTypes.INTEGER,
            total_experience_duration_months_breakdown_department: DataTypes.JSONB,
            total_experience_duration_months_breakdown_management_level: DataTypes.JSONB,
            projected_base_salary_p25: DataTypes.TEXT,
            projected_base_salary_median: DataTypes.TEXT,
            projected_base_salary_p75: DataTypes.TEXT,
            projected_base_salary_period: DataTypes.TEXT,
            projected_base_salary_currency: DataTypes.TEXT,
            projected_base_salary_updated_at: DataTypes.TEXT,
            projected_additional_salary: DataTypes.JSONB,
            projected_additional_salary_period: DataTypes.TEXT,
            projected_additional_salary_currency: DataTypes.TEXT,
            projected_additional_salary_updated_at: DataTypes.TEXT,
            projected_total_salary_p25: DataTypes.TEXT,
            projected_total_salary_median: DataTypes.TEXT,
            projected_total_salary_p75: DataTypes.TEXT,
            projected_total_salary_period: DataTypes.TEXT,
            projected_total_salary_currency: DataTypes.TEXT,
            projected_total_salary_updated_at: DataTypes.TEXT,
            last_graduation_date: DataTypes.TEXT,
            education_degrees: DataTypes.ARRAY(DataTypes.TEXT),
            recommendations_count: DataTypes.INTEGER,
            recommendations: DataTypes.JSONB,
            activity: DataTypes.JSONB,
            patents_count: DataTypes.INTEGER,
            patents_topics: DataTypes.ARRAY(DataTypes.TEXT),
            publications_count: DataTypes.INTEGER,
            publications_topics: DataTypes.ARRAY(DataTypes.TEXT),
            projects_count: DataTypes.INTEGER,
            projects_topics: DataTypes.ARRAY(DataTypes.TEXT),
            github_url: DataTypes.TEXT,
            github_username: DataTypes.TEXT,
            github_mapping_confidence: DataTypes.TEXT,
            github_contributions_count: DataTypes.TEXT,
            github_repos_summary: DataTypes.JSONB,
            profile_root_field_changes_summary: DataTypes.JSONB,
            profile_collection_field_changes_summary: DataTypes.JSONB,
            experience_recently_started: DataTypes.JSONB,
            experience_recently_closed: DataTypes.JSONB,
            hs_month: DataTypes.TEXT,
            is_deleted: DataTypes.BOOLEAN,
            is_parent: DataTypes.BOOLEAN,
            is_working: DataTypes.BOOLEAN,
            active_experience_company_id: DataTypes.TEXT,
            active_experience_description: DataTypes.TEXT,
            is_decision_maker: DataTypes.BOOLEAN,
            checked_at: DataTypes.DATE,
            changed_at: DataTypes.DATE,
            experience_change_last_identified_at: DataTypes.TEXT,
            created_at: DataTypes.DATE,
            updated_at: DataTypes.DATE,
        },
        {
            tableName: "profiles",
            schema: "linkedin",
            timestamps: true,
        }
    );

    return Profile;
};